import React from 'react';
import { Link } from 'react-router-dom';
import { FileText, ArrowLeft, AlertTriangle, CheckCircle, XCircle, User } from 'lucide-react';

const TermsConditions = () => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-[#FDFD96] via-[#fffaaa] to-[#f0f0f0] py-12 px-4">
      {/* Animated Background Elements */}
      <div className="fixed top-20 left-10 w-64 h-64 bg-green-400/10 rounded-full blur-3xl animate-pulse"></div>
      <div className="fixed bottom-20 right-10 w-96 h-96 bg-yellow-400/10 rounded-full blur-3xl animate-pulse" style={{ animationDelay: '1s' }}></div>
      
      <div className="max-w-4xl mx-auto relative z-10">
        {/* Back Button */}
        <Link 
          to="/" 
          className="inline-flex items-center gap-2 mb-8 px-4 py-2 bg-white border-2 border-black font-bold text-sm shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:translate-x-1 hover:translate-y-1 hover:shadow-none transition-all"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to Home
        </Link>

        {/* Header */}
        <div className="bg-white border-4 border-black p-8 shadow-[12px_12px_0px_0px_rgba(0,0,0,1)] mb-8">
          <div className="flex items-center gap-4 mb-4">
            <div className="bg-green-600 p-3 border-2 border-black">
              <FileText className="w-8 h-8 text-white" />
            </div>
            <h1 className="text-4xl font-black uppercase tracking-tighter text-black">
              Terms & Conditions
            </h1>
          </div>
          <p className="font-bold text-gray-600">Last Updated: February 2026</p>
        </div>

        {/* Content */}
        <div className="bg-white border-4 border-black p-8 shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] space-y-6">
          <section>
            <h2 className="text-xl font-black uppercase mb-3 flex items-center gap-2">
              <CheckCircle className="w-5 h-5 text-green-600" />
              1. Acceptance of Terms
            </h2>
            <p className="text-gray-700 font-medium leading-relaxed">
              By accessing and using Resume Pro, you accept and agree to be bound by the terms and provision of this agreement. 
              If you do not agree to these terms, please do not use our service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-black uppercase mb-3 flex items-center gap-2">
              <User className="w-5 h-5 text-green-600" />
              2. Eligibility & Account
            </h2>
            <p className="text-gray-700 font-medium leading-relaxed">
              Our service is available only to IIIT Surat students with a valid @iiitsurat.ac.in email address. 
              You must provide accurate and complete information when creating an account. You are responsible for maintaining 
              the confidentiality of your account credentials.
            </p>
          </section>

          <section>
            <div className="bg-amber-50 border-l-4 border-amber-500 p-4 mb-4">
              <div className="flex items-start gap-3">
                <AlertTriangle className="w-5 h-5 text-amber-600 mt-0.5 flex-shrink-0" />
                <div>
                  <p className="font-bold text-amber-800">Important Password Policy</p>
                  <p className="text-amber-700 text-sm mt-1">
                    Once set, your password <span className="font-bold">cannot be changed</span>. 
                    Please choose your password carefully and store it securely.
                  </p>
                </div>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-black uppercase mb-3">
              3. Use License
            </h2>
            <p className="text-gray-700 font-medium leading-relaxed">
              Permission is granted to temporarily use Resume Pro for personal, non-commercial resume analysis purposes only. 
              This is the grant of a license, not a transfer of title. You may not modify, copy, distribute, transmit, 
              display, perform, reproduce, publish, license, create derivative works from, transfer, or sell any content 
              from this service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-black uppercase mb-3">
              4. AI-Generated Content Disclaimer
            </h2>
            <p className="text-gray-700 font-medium leading-relaxed">
              Resume Pro uses Artificial Intelligence to analyze resumes and generate suggestions. While we strive for accuracy, 
              AI models can make mistakes, hallucinate facts, or provide outdated information. All suggestions and content 
              generated by our AI should be reviewed manually before use. We are not responsible for any decisions made 
              based on AI-generated content.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-black uppercase mb-3">
              5. User Content
            </h2>
            <p className="text-gray-700 font-medium leading-relaxed">
              You retain ownership of any content you upload to Resume Pro, including your resume documents. By uploading 
              content, you grant us permission to process and analyze it for providing our services. You represent and 
              warrant that you have the legal right to upload and share such content.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-black uppercase mb-3 flex items-center gap-2">
              <XCircle className="w-5 h-5 text-red-600" />
              6. Prohibited Uses
            </h2>
            <p className="text-gray-700 font-medium leading-relaxed mb-3">
              You may not use our service to:
            </p>
            <ul className="list-disc list-inside space-y-2 text-gray-700 font-medium ml-4">
              <li>Upload false or misleading information</li>
              <li>Violate any applicable laws or regulations</li>
              <li>Infringe upon the rights of others</li>
              <li>Attempt to gain unauthorized access to our systems</li>
              <li>Use the service for any unlawful purpose</li>
              <li>Submit content containing viruses or malicious code</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-black uppercase mb-3">
              7. Limitation of Liability
            </h2>
            <p className="text-gray-700 font-medium leading-relaxed">
              Resume Pro is provided "as is" without any warranties, express or implied. We do not guarantee that the 
              service will be error-free, secure, or continuously available. In no event shall we be liable for any 
              indirect, incidental, special, or consequential damages arising out of your use of the service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-black uppercase mb-3">
              8. Privacy
            </h2>
            <p className="text-gray-700 font-medium leading-relaxed">
              Your privacy is important to us. Please review our 
              <Link to="/privacy-policy" className="text-blue-600 font-bold hover:underline mx-1">Privacy Policy</Link>
              to understand how we collect, use, and protect your information.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-black uppercase mb-3">
              9. Changes to Terms
            </h2>
            <p className="text-gray-700 font-medium leading-relaxed">
              We reserve the right to modify these terms at any time. Your continued use of Resume Pro after any 
              modifications indicates your acceptance of the new terms. It is your responsibility to review 
              these terms periodically.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-black uppercase mb-3">
              10. Contact Information
            </h2>
            <p className="text-gray-700 font-medium leading-relaxed">
              If you have any questions about these Terms and Conditions, please contact us through our 
              <Link to="/contact" className="text-blue-600 font-bold hover:underline mx-1">Contact Page</Link>.
            </p>
          </section>
        </div>

        {/* Footer Note */}
        <div className="mt-8 text-center">
          <p className="text-sm font-bold text-gray-500">
            © 2026 Resume Pro Inc. All rights reserved.
          </p>
        </div>
      </div>
    </div>
  );
};

export default TermsConditions;
